// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTh0REvTgZ12cyHYmScJaTzvtZH00EOc0',
    appId: '1:32830922008:web:fd0834386c169a5b61126d',
    messagingSenderId: '32830922008',
    projectId: 'senior-project-3b821',
    authDomain: 'senior-project-3b821.firebaseapp.com',
    storageBucket: 'senior-project-3b821.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMSaqcrAE7gjdeB5hXB3wgdoxyjNvZnUQ',
    appId: '1:32830922008:android:3539f3bedc2cb50361126d',
    messagingSenderId: '32830922008',
    projectId: 'senior-project-3b821',
    storageBucket: 'senior-project-3b821.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC03jLJ_ZjqOKMc_K6nmY93El9cfi3f1ys',
    appId: '1:32830922008:ios:4caed3f830ddb22461126d',
    messagingSenderId: '32830922008',
    projectId: 'senior-project-3b821',
    storageBucket: 'senior-project-3b821.appspot.com',
    iosBundleId: 'com.example.facialReg',
  );

}